//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Skunk.Website.Models
{
	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : Base
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Competition Feed: The RSS feed of the competition to show in the homepage.
		///</summary>
		[ImplementPropertyType("competitionFeed")]
		public string CompetitionFeed
		{
			get { return this.GetPropertyValue<string>("competitionFeed"); }
		}

		///<summary>
		/// Header visuals: Select the images from the media library to use in the carousel.
		///</summary>
		[ImplementPropertyType("headerVisuals")]
		public IEnumerable<IPublishedContent> HeaderVisuals
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("headerVisuals"); }
		}

		///<summary>
		/// Main News Item: The main news item.
		///</summary>
		[ImplementPropertyType("mainNewsItem")]
		public IEnumerable<IPublishedContent> MainNewsItem
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("mainNewsItem"); }
		}

		///<summary>
		/// Page description: The description meta-tag, used for search engine indexing.
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public string PageDescription
		{
			get { return this.GetPropertyValue<string>("pageDescription"); }
		}

		///<summary>
		/// Page title: The title of the page displayed in the browser.
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// Sponsor Logo 1: The first sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo1")]
		public IPublishedContent SponsorLogo1
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo1"); }
		}

		///<summary>
		/// Sponsor Logo 10
		///</summary>
		[ImplementPropertyType("sponsorLogo10")]
		public IPublishedContent SponsorLogo10
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo10"); }
		}

		///<summary>
		/// Sponsor Logo 11
		///</summary>
		[ImplementPropertyType("sponsorLogo11")]
		public IPublishedContent SponsorLogo11
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo11"); }
		}

		///<summary>
		/// Sponsor Logo 12
		///</summary>
		[ImplementPropertyType("sponsorLogo12")]
		public IPublishedContent SponsorLogo12
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo12"); }
		}

		///<summary>
		/// Sponsor Logo 2: The second sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo2")]
		public IPublishedContent SponsorLogo2
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo2"); }
		}

		///<summary>
		/// Sponsor Logo 3: The third sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo3")]
		public IPublishedContent SponsorLogo3
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo3"); }
		}

		///<summary>
		/// Sponsor Logo 4: The fourth sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo4")]
		public IPublishedContent SponsorLogo4
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo4"); }
		}

		///<summary>
		/// Sponsor Logo 5: The fifth sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo5")]
		public IPublishedContent SponsorLogo5
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo5"); }
		}

		///<summary>
		/// Sponsor Logo 6: The sixth sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo6")]
		public IPublishedContent SponsorLogo6
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo6"); }
		}

		///<summary>
		/// Sponsor Logo 7: The seventh sponsor logo to display in the footer of every page.
		///</summary>
		[ImplementPropertyType("sponsorLogo7")]
		public IPublishedContent SponsorLogo7
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo7"); }
		}

		///<summary>
		/// Sponsor Logo 8
		///</summary>
		[ImplementPropertyType("sponsorLogo8")]
		public IPublishedContent SponsorLogo8
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo8"); }
		}

		///<summary>
		/// Sponsor Logo 9
		///</summary>
		[ImplementPropertyType("sponsorLogo9")]
		public IPublishedContent SponsorLogo9
		{
			get { return this.GetPropertyValue<IPublishedContent>("sponsorLogo9"); }
		}

		///<summary>
		/// Sponsor Url 1: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl1")]
		public string SponsorUrl1
		{
			get { return this.GetPropertyValue<string>("sponsorUrl1"); }
		}

		///<summary>
		/// Sponsor Url 10
		///</summary>
		[ImplementPropertyType("sponsorUrl10")]
		public string SponsorUrl10
		{
			get { return this.GetPropertyValue<string>("sponsorUrl10"); }
		}

		///<summary>
		/// Sponsor Url 11
		///</summary>
		[ImplementPropertyType("sponsorUrl11")]
		public string SponsorUrl11
		{
			get { return this.GetPropertyValue<string>("sponsorUrl11"); }
		}

		///<summary>
		/// Sponsor Url 12
		///</summary>
		[ImplementPropertyType("sponsorUrl12")]
		public string SponsorUrl12
		{
			get { return this.GetPropertyValue<string>("sponsorUrl12"); }
		}

		///<summary>
		/// Sponsor Url 2: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl2")]
		public string SponsorUrl2
		{
			get { return this.GetPropertyValue<string>("sponsorUrl2"); }
		}

		///<summary>
		/// Sponsor Url 3: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl3")]
		public string SponsorUrl3
		{
			get { return this.GetPropertyValue<string>("sponsorUrl3"); }
		}

		///<summary>
		/// Sponsor Url 4: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl4")]
		public string SponsorUrl4
		{
			get { return this.GetPropertyValue<string>("sponsorUrl4"); }
		}

		///<summary>
		/// Sponsor Url 5: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl5")]
		public string SponsorUrl5
		{
			get { return this.GetPropertyValue<string>("sponsorUrl5"); }
		}

		///<summary>
		/// Sponsor Url 6: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl6")]
		public string SponsorUrl6
		{
			get { return this.GetPropertyValue<string>("sponsorUrl6"); }
		}

		///<summary>
		/// Sponsor Url 7: The Url to the homepage of the sponsor.
		///</summary>
		[ImplementPropertyType("sponsorUrl7")]
		public string SponsorUrl7
		{
			get { return this.GetPropertyValue<string>("sponsorUrl7"); }
		}

		///<summary>
		/// Sponsor Url 8
		///</summary>
		[ImplementPropertyType("sponsorUrl8")]
		public string SponsorUrl8
		{
			get { return this.GetPropertyValue<string>("sponsorUrl8"); }
		}

		///<summary>
		/// Sponsor Url 9
		///</summary>
		[ImplementPropertyType("sponsorUrl9")]
		public string SponsorUrl9
		{
			get { return this.GetPropertyValue<string>("sponsorUrl9"); }
		}

		///<summary>
		/// Sub News Item 1: Sub news item number one.
		///</summary>
		[ImplementPropertyType("subNewsItem1")]
		public IEnumerable<IPublishedContent> SubNewsItem1
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("subNewsItem1"); }
		}

		///<summary>
		/// Sub News Item 2: Sub news item number two.
		///</summary>
		[ImplementPropertyType("subNewsItem2")]
		public IEnumerable<IPublishedContent> SubNewsItem2
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("subNewsItem2"); }
		}

		///<summary>
		/// Sub News Item 3: Sub news item number three.
		///</summary>
		[ImplementPropertyType("subNewsItem3")]
		public IEnumerable<IPublishedContent> SubNewsItem3
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("subNewsItem3"); }
		}

		///<summary>
		/// Webshop Url: Enter a Url to an external webshop, this is optional.
		///</summary>
		[ImplementPropertyType("webshopUrl")]
		public string WebshopUrl
		{
			get { return this.GetPropertyValue<string>("webshopUrl"); }
		}
	}
}
